version: '3.8'
services: 
  database:
    image: mongo
    restart: always 
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes: 
      - my_data:/data/db
    ports: 
      - 27017:27017
    networks: 
      - base-network
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - database
    volumes: 
      - /app/node_modules
      - ./:/app 
    ports: 
      - "5000:5000"
    networks: 
      - base-network
  
volumes: 
  my_data:
networks: 
  base-network: